name: iOS CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Test
        run: |
          xcodebuild test \
            -project WallaMarvel.xcodeproj \
            -scheme WallaMarvel \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            -resultBundlePath TestResults.xcresult \
            -skipPackagePluginValidation \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults.xcresult
